package ru.ruskonnect.smoothgl.mixin;

import net.minecraft.client.render.entity.feature.ArmorFeatureRenderer;
import net.minecraft.client.render.entity.feature.CapeFeatureRenderer;
import net.minecraft.client.render.entity.feature.ElytraFeatureRenderer;
import net.minecraft.client.render.entity.state.EntityRenderState;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.client.render.VertexConsumerProvider;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import ru.ruskonnect.smoothgl.SmoothGLClient;
import ru.ruskonnect.smoothgl.config.SmoothConfig;

/**
 * Skip armor / cape / elytra layer rendering past a distance.
 *
 * <p>Unlike the full entity cull (which drops everything including the
 * silhouette), this only cancels expensive cosmetic layers, so the player
 * is still visible — important for PvP. Cull distance is smaller than the
 * full entity cull on purpose (default 32 vs 64).</p>
 *
 * <p>Targets the synthetic bridge method (MatrixStack, VertexConsumerProvider,
 * int, EntityRenderState, float, float) generated by the compiler for each
 * concrete subclass; cancelling the bridge prevents the typed implementation
 * from running.</p>
 */
@Mixin({
    ArmorFeatureRenderer.class,
    CapeFeatureRenderer.class,
    ElytraFeatureRenderer.class
})
public abstract class FeatureLayerCullMixin {

    @Inject(
        method = "render(Lnet/minecraft/client/util/math/MatrixStack;Lnet/minecraft/client/render/VertexConsumerProvider;ILnet/minecraft/client/render/entity/state/EntityRenderState;FF)V",
        at = @At("HEAD"),
        cancellable = true,
        require = 0
    )
    private void smoothgl$cullDistantLayer(MatrixStack matrices, VertexConsumerProvider vcp,
                                            int light, EntityRenderState state,
                                            float limbAngle, float limbDistance,
                                            CallbackInfo ci) {
        SmoothConfig cfg = SmoothGLClient.config();
        if (cfg == null || !cfg.enableLayerCull || state == null) return;
        double maxSq = cfg.layerCullDistance * cfg.layerCullDistance;
        if (state.squaredDistanceToCamera > maxSq) {
            ci.cancel();
        }
    }
}
